# .github/workflows/release.yml
name: Build & Release Electron App

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run make
        env:
          WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List build output (macOS) # Keep for debugging if needed
        if: runner.os == 'macOS'
        run: ls -R out/make
        shell: bash
        continue-on-error: true

      # Upload OS-specific artifacts
      - name: Upload Windows Artifact (${{ matrix.os }})
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-Windows
          path: out/make/**/*.exe
          if-no-files-found: error

      - name: Upload macOS Artifact (${{ matrix.os }})
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-macOS
          path: out/make/**/*.zip # Expecting ZIP for macOS
          if-no-files-found: error

      - name: Upload Linux Artifact (${{ matrix.os }})
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-Linux
          path: out/make/**/*.deb
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to create releases/upload assets

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files (for debugging)
        run: find artifacts -type f

      # --- Reverted to simpler release action (no renaming) ---
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # body: Optional release notes can go here
          draft: false
          prerelease: false
          # Use glob patterns to find assets within the downloaded artifact subdirectories
          # This uploads files with their original names from the build process
          files: |
            artifacts/build-artifacts-Windows/**/*.exe
            artifacts/build-artifacts-macOS/**/*.zip
            artifacts/build-artifacts-Linux/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
